Organizations:

  - &Manufacturer
    Name: ManufacturerMSP
    ID: ManufacturerMSP
    MSPDir: crypto-config/peerOrganizations/manufacturer.example.com/msp
    AnchorPeers:
      - Host: peer0.manufacturer.example.com
        Port: 7051

  - &Distributor
    Name: DistributorMSP
    ID: DistributorMSP
    MSPDir: crypto-config/peerOrganizations/distributor.example.com/msp
    AnchorPeers:
      - Host: peer0.distributor.example.com
        Port: 9051

  - &Retailer
    Name: RetailerMSP
    ID: RetailerMSP
    MSPDir: crypto-config/peerOrganizations/retailer.example.com/msp
    AnchorPeers:
      - Host: peer0.retailer.example.com
        Port: 11051

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Profiles:
  SupplyChainChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Manufacturer
        - *Distributor
        - *Retailer
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"

  SupplyOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Manufacturer
        - *Distributor
        - *Retailer
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Manufacturer
          - *Distributor
          - *Retailer
