version: '3.7'

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050

  peer0.manufacturer.example.com:
    container_name: peer0.manufacturer.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.manufacturer.example.com
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_ADDRESS=peer0.manufacturer.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    volumes:
      - ./crypto-config/peerOrganizations/manufacturer.example.com/peers/peer0.manufacturer.example.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
    depends_on:
      - orderer.example.com

  peer0.distributor.example.com:
    container_name: peer0.distributor.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.distributor.example.com
      - CORE_PEER_LOCALMSPID=DistributorMSP
      - CORE_PEER_ADDRESS=peer0.distributor.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    volumes:
      - ./crypto-config/peerOrganizations/distributor.example.com/peers/peer0.distributor.example.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:9051
    depends_on:
      - orderer.example.com

  peer0.retailer.example.com:
    container_name: peer0.retailer.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.retailer.example.com
      - CORE_PEER_LOCALMSPID=RetailerMSP
      - CORE_PEER_ADDRESS=peer0.retailer.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    volumes:
      - ./crypto-config/peerOrganizations/retailer.example.com/peers/peer0.retailer.example.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 11051:11051
    depends_on:
      - orderer.example.com
